services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: trackmybugs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: trackmybugs
      DB_USER: postgres
      DB_PASSWORD: password
      JWT_SECRET: your_jwt_secret_here
      GIN_MODE: release
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080/api/v1
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  db_data: 